### ISSUE TITLE
Playground block: Activate button going out of viewport

### ISSUE THREAD

**Issue by adamziel** [WordPress/playground-tools#272]
When there's a lot of code, the activate preview button is vertically centered relative to the code editor height, which can make it go off screen:

![CleanShot 2024-05-21 at 17 40 51@2x](https://github.com/WordPress/playground-tools/assets/205419/ddc04dac-e02c-4551-9509-1708cb098c62)

cc @brandonpayton

**Comment by brandonpayton** [comment]
Ouch. That's a strange and annoying visual bug. Added to my list to take a look in the next day or so.

**Comment by brandonpayton** [comment]
@adamziel in my testing, this is not related to the height of the code because removing much of the code didn't affect the button position.

This issue appears to be due to a rule in the wpcom p2020 theme:
```
.p2-editor .wp-block-group :last-child,.entry-content .wp-block-group :last-child,.comment-content .wp-block-group :last-child {
    margin-bottom: 0;
}
```

This rule applies to the button that [we style with `margin: auto`](https://github.com/WordPress/playground-tools/blob/3da7569d369ead88a4ca1d842fe015d1295d08bd/packages/wordpress-playground-block/src/style.scss#L186-L187) and causes it to be rendered at the bottom of the pane.
